server:
  port: 8080
  contextPath: /SpringBootApp
datasource:
  springbootapp:
    url: jdbc:mysql://127.0.0.1:3306/ihub
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect  
